cstor/config/routes.rb
Rails.application.routes.draw do

  resources :resources

  get '/secret', to: 'resources#secretindex'

  resources :tags, only: [:new, :create, :show]

  root 'resources#index'

  resources :users, except: [:index, :update, :edit, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :resources do
    resources :likes, only: [:create, :destroy]
  end

  get '/4XuibdvyYYkaulCUp2CN', to: 'users#admin_new'
  post '/4XuibdvyYYkaulCUp2CN', to: 'users#admin_create'

end

cstor/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :liker, class_name: "User"
  belongs_to :resource
end

cstor/app/models/resource.rb
class Resource < ActiveRecord::Base
  has_many :likes
  belongs_to :teacher, class_name: "User"
  has_many :likers, through: :likes
  has_many :resource_tags
  has_many :tags, through: :resource_tags

  validates :title, { presence: true, uniqueness: true}
  validates :abstract, { presence: true, uniqueness: true}
  validates :url, { presence: true }

  def like_by_user(user)
    self.likes.find_by(liker_id: user.id)
  end


  def stringify_tags(tags_array)
    word = ""
    tags_array.each_with_index do |tag, index|
      if index+1 == tags_array.length
        word << tag.name
      else
        word << "#{tag.name}, "
      end
    end
    word
  end

  def arrayify_string(string, resource)
    tags = string.split(',').map! {|tag| tag.lstrip}
    tags.each do |tag|
      if Tag.find_by(name: tag)
        resource.tags << Tag.find_by(name: tag)
      else
        resource.tags << Tag.create(name: tag)
      end
    end
  end

  def viewable_by_student?
    self.teacher_only == false
  end

  def self.secret_list
    self.select{|r| r.viewable_by_student? == false}
  end
end

cstor/app/models/resource_tag.rb
class ResourceTag < ActiveRecord::Base
  belongs_to :resource
  belongs_to :tag
end

cstor/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :resource_tags
  has_many :resources, through: :resource_tags
end

cstor/app/models/user.rb
class User < ActiveRecord::Base
  has_many :resources, foreign_key: :teacher_id
  has_many :likes, foreign_key: :liker_id
  has_many :liked_resources, through: :likes, source: :resource

  has_secure_password

  validates :username, :email, presence: true
  validates :email, uniqueness: true
end

cstor/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @_current ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def set_user(user)
    session[:user_id] = user.id
  end
end

cstor/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
  end

  def create
    path = URI(request.referer).path
    @like = Like.new(liker_id: current_user.id, resource_id: params[:resource_id])
    if @like.save
      redirect_to :back
    else
      flash[:notice] = "There was an error"
      redirect_to path
    end
  end

  def destroy
    path = URI(request.referer).path
    @like = Like.find_by(liker_id: current_user.id, resource_id: params[:resource_id])
    @like.destroy
    redirect_to :back
  end
end

cstor/app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @resources = Resource.all.order(updated_at: :desc)
    @resources = @resources.page(params[:page]).per(8)
  end

  def secretindex
    @resources = Resource.order(updated_at: :desc)
    if current_user.admin == true
      @resources = @resources.secret_list
      render 'secret_index'
    else
      redirect_to '/'
    end
  end

  def show
    @resource = Resource.find(params[:id])
    @tags = @resource.tags
    @likes = @resource.likes
  end


  def new
    if !current_user.admin
      redirect_to resources_path
    end
  end

  def create
    @resource = current_user.resources.new(resource_params)
    if @resource.save && current_user.admin
      # tags = tag_params[:tag].split(',').map! {|tag| tag.lstrip}
      # tags.each do |tag|
      #   if Tag.find_by(name: tag)
      #     @resource.tags << Tag.find_by(name: tag)
      #   else
      #     @resource.tags << Tag.create(name: tag)
      #   end
      # end
      @resource.arrayify_string(tag_params[:tag], @resource)
      redirect_to @resource, notice: "Your Resource was a success!"
    else
      @tags = tag_params[:tag]
      @errors = @resource.errors.full_messages
      render :new, status: 400
    end
  end

  def edit
    if !current_user.admin
      redirect_to resource_path
    end
   @resource = Resource.find(params[:id])
   @tags_string = @resource.stringify_tags(@resource.tags)
  end

  def update
    @resource = Resource.find(params[:id])
    @resource.arrayify_string(tag_params[:tag], @resource)
    @resource.update_attributes(resource_params)
    if @resource.save
      redirect_to resource_path(@resource)
    else
      @errors = @resource.errors.full_messages
      render 'edit'
    end
  end

 def destroy
  if current_user.admin == true
    @resource = Resource.find(params[:id])
    @resource.destroy
  end
  redirect_to resources_path
end

private

def resource_params
  params.require(:resource).permit(:title, :abstract, :url, :teacher_only)
end

def tag_params
  params.require(:resource).permit(:tag)
end

end

cstor/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      set_user(user)

      redirect_to resources_path
    else
      @errors = ["Login failed."]
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to resources_path
  end
end

cstor/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
  end

  def create
  end

  def show
    @tag = Tag.find(params[:id])
    @resources = @tag.resources
  end



end

cstor/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @show_user = find_user
    if @show_user.admin && !current_user.admin
      redirect_to resources_path
    end
  end

  def admin_new
    @user = User.new
    render 'new_admin'
  end

  def admin_create
    @user = User.new(user_params)
    @user.admin = true
    if @user.save
      session[:user_id] = @user.id
      redirect_to resources_path
    else
      @errors = @user.errors.full_messages
      render "new"
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      set_user(@user)
      redirect_to resources_path
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :admin, :password)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end
end

cstor/app/helpers/application_helper.rb
module ApplicationHelper

end

cstor/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @_current ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def set_user(user)
    session[:user_id] = user.id
  end
end

cstor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cstor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"

</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand"> CSTOR </a>
      </div>
      <ul class="nav navbar-nav">

        <li><a><%= link_to "Home", resources_path %></a></li>
        <% if logged_in? %>
        <li><a><%= link_to "Logout", session_path(current_user.id), method: :delete %></a></li>
        <li><a><%= link_to "My Profile", user_path(current_user.id)%></a></li>
        <li><a>Signed in as <%=  current_user.username %></a></li>
        <% end %>
      </ul>

      <% if !logged_in? %>
      <ul class="nav navbar-nav navbar-right">
       <li><a><span class="glyphicon glyphicon-user"></span><%= link_to "Register", new_user_path %></a></li>
        <li><a><span class="glyphicon glyphicon-log-in"></span> <%= link_to "Log In", new_session_path %></a></li>
      </ul>
       <% end %>
    </div>
  </nav>

  <div class="container-fluid">
    <%= yield %>
  </body>
  </html>

cstor/app/views/resources/edit.html.erb
<div class="container-fluid">
	<%= render partial: '/users/errors' %>

	<%=form_for @resource,:html => {:class => "form-horizontal"} do |f| %>

 <div class="form-group">
  <%= f.label :title, class: "col-sm-2 control-label" %><br>
  <%= f.text_field :title, class: 'form-inline'  %>
</div>

<div class="form-group">
  <%=f.label :abstract, class: "col-sm-2 control-label"%><br>
  <%= f.text_area :abstract, class: 'form-inline'  %>
</div>

<div class="form-group">
  <%= f.label :url, class: "col-sm-2 control-label" %><br>
  <%= f.text_field :url, class: 'form-inline'  %>
</div>

<div class="form-group">
  <%= f.check_box :teacher_only, class: 'form-inline'  %>
  <%= f.label :teacher_only, "Teachers Only", class: "col-sm-2 control-label" %>
</div>

<div class="form-group">
  <%= f.label :tags, class: "col-sm-2 control-label" %> <small>(separate by commas)</small> <br>
  <input id="resource_tag" name="resource[tag]" type="text">
</div>

<div class="form-group">
  <%= f.label "Submit", class: "col-sm-2 control-label" %><br>
  <%= f.submit %>
</div>

<% end %>
</div>

cstor/app/views/resources/index.html.erb
<div class="container-fluid">


  Tags:<%= render partial: "tags/tagmenu" %><br><br>
  <hr>

  <% if current_user && current_user.admin %>
  <p><%= link_to 'Create New Resource', new_resource_path %></p>
  <p><%= link_to 'Teacher Learning Resources', secret_path %></p>
  <% end %>

  <div class="panel panel-info">
    <% @resources.each do |resource| %>
    <% if resource.viewable_by_student? %>
    <div class="panel-heading">
      <h3 class="panel-title"><a href="/resources/<%= resource.id%>"><%= resource.title %></a> </h3>

    </div>
    <div class="panel-body">
      <p> <%= resource.abstract %> </p>
      <p> <em><%= resource.teacher.username %></em> </p>
      <% if logged_in? %>
      <% if !resource.likers.include?(current_user)%>

      <%= form_for :like, url: "/resources/#{resource.id}/likes" do |f| %>
      <%= f.submit "Like" %>
      <% end %>

      <% else %>

      <% if resource.like_by_user(current_user) != nil %>
      <%= form_for [resource, resource.like_by_user(current_user)], method: :delete do |f| %>
      <%= f.submit "Unlike" %>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
    </div>
    <% end %>
    <% end %>
  </div>

  <div class="pagination">
    <%= paginate @resources %>
  </div>

</div>

cstor/app/views/resources/new.html.erb
<div class="container-fluid">
	<%= render partial: '/users/errors' %>
	<span class="border-0">
		<%=form_for :resource,:html => {:class => "form-horizontal"}, url: resources_path do |f| %>


		<div class="form-group">
			<%= f.label :title, class: "col-sm-2 control-label" %><br>
			<%= f.text_field :title, class: 'form-inline'  %>
		</div>

		<div class="form-group">
			<%=f.label :abstract, class: "col-sm-2 control-label"%><br>
			<%= f.text_area :abstract, class: 'form-inline'  %>
		</div>

		<div class="form-group">
		<%= f.label :url, class: "col-sm-2 control-label" %><br>
			<%= f.text_field :url, class: 'form-inline'  %>
		</div>

		<div class="form-group">
			<%= f.check_box :teacher_only, class: 'form-inline'  %>
			<%= f.label :teacher_only, "Teachers Only", class: "col-sm-2 control-label" %>
		</div>

		<div class="form-group">
			<%= f.label :tags, class: "col-sm-2 control-label" %> <small>(separate by commas)</small> <br>
			<input id="resource_tag" name="resource[tag]" type="text">
		</div>

		<div class="form-group">
				<%= f.label "Submit", class: "col-sm-2 control-label" %><br>
				<%= f.submit %>
		</div>

		<% end %>
	</span>
</div>

cstor/app/views/resources/secret_index.html.erb
<div class="container-fluid">

<div class="panel panel-info">
  <% @resources.each do |resource| %>
  <% if !resource.viewable_by_student? %>
    <div class="panel-heading">
      <h3 class="panel-title"><a href="/resources/<%= resource.id%>"><%= resource.title %></a></h3>

    </div>
    <div class="panel-body">
      <p> <%= resource.abstract %> </p>
      <p> <em><%= resource.teacher.username %></em> </p>

      <% if !resource.likers.include?(current_user)%>

      <%= form_for :like, url: "/resources/#{resource.id}/likes" do |f| %>
      <%= f.submit "Like" %>
      <% end %>

      <% else %>

      <% if resource.like_by_user(current_user) != nil %>
      <%= form_for [resource, resource.like_by_user(current_user)], method: :delete do |f| %>
      <%= f.submit "Unlike" %>
      <% end %>
      <% end %>
      <% end %>

    </div>
      <% end %>
    <% end %>
  </div>

</div>

cstor/app/views/resources/show.html.erb
<div class="container-fluid">
  <div class="panel panel-info">
   <div class="panel-heading">
<h3 class="panel-title"><%= @resource.title.capitalize %> </h3>
   </div>
<% @tags.each do |tag| %>
<button><%= link_to tag.name, tag_path(tag) %></button>
<% end %>
<hr>
<p>
<div class="panel-body">
  <b>Abstract:</b><br>
  <p><%= @resource.abstract %> </p>
  <p>
    <b>Link:</b><br>
    <a href="<%= @resource.url %>"><%= @resource.url%> </a>
  </p>
  <p> <b>Author:</b> <em><%= @resource.teacher.username %></em> </p>

  <p> added on: <%=@resource.created_at.strftime("%m-%d-%Y")  %></p>

<% if current_user && current_user.admin %>
  <%= form_for @resource, method: :delete do |f| %>
  <%= f.submit "Delete" %>
  <% end %>

<%= link_to 'Update Resource', edit_resource_path %>
<% end  %>
</div>
</div>

cstor/app/views/tags/_tagmenu.html.erb
<div class= "container-fluid"
<% Tag.all.each do |tag| %>
  <button><%= link_to tag.name, tag_path(tag) %></button>
<% end %>
</div>

cstor/app/views/tags/show.html.erb
<div class="container-fluid">
  <h2> Cstor | <%= @tag.name.capitalize %> </h2>
  <hr>


<!-- pagination here?
-->

Tags:<%= render partial: "tags/tagmenu" %><br><br>

  <div class="panel panel-info">
    <% @resources.each do |resource| %>
    <% if resource.viewable_by_student? %>
    <div class="panel-heading">
      <h3 class="panel-title"><a href="/resources/<%= resource.id%>"><%= resource.title %></a> </h3>

    </div>
    <div class="panel-body">
      <p> <%= resource.abstract %> </p>
      <p> <em><%= resource.teacher.username %></em> </p>

      <% if !resource.likers.include?(current_user)%>

      <%= form_for :like, url: "/resources/#{resource.id}/likes" do |f| %>
      <%= f.submit "Like" %>
      <% end %>

      <% else %>

      <% if resource.like_by_user(current_user) != nil %>
      <%= form_for [resource, resource.like_by_user(current_user)], method: :delete do |f| %>
      <%= f.submit "Unlike" %>
      <% end %>
      <% end %>
      <% end %>

    </div>
    <% end %>
    <% end %>
  </div>
</div>

cstor/app/views/users/_errors.html.erb
<% if @errors %>
<div class="alert alert-danger" role="alert">
  <% @errors.each do |error| %>
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="error"><%= error %><br></span>
  <% end %>
<% end %><br>
</div>

cstor/app/views/users/new.html.erb
<div class='container'>
	<span class="border-0">
		<h1>Create an Account with Cstor</h1>
		<%= render partial: 'errors' %>

		<%= form_for :user, :html => {:class => "form-horizontal"}, url: '/users' do |f| %>
		<div class="form-group">
			<%= f.label :username, "Username:", class: "col-sm-2 control-label" %>
			<%= f.text_field :username, class: 'form-inline' %><br>
			</div>
			<div class="form-group">
			<%= f.label :email, "Email:", class: "col-sm-2 control-label" %>
			<%= f.text_field :email, class: 'form-inline' %><br>
			</div>
			<div class="form-group">
			<%= f.label :password, "Password:", class: "col-sm-2 control-label" %>
			<%= f.password_field :password, class: 'form-inline' %><br>
			<%= f.submit "Register!" %>
			</div>
			<% end %>
		</div>
	</span>
</div>

cstor/app/views/users/new_admin.html.erb
<div class='container-fluid'>
  <h1>Create an Admin Account with Cstor</h1>

  <%= render partial: 'errors' %>


  <%= form_for :user, :html => {:class => "form-horizontal"}, url: '/4XuibdvyYYkaulCUp2CN' do |f| %>


  <div class="form-group">
    <%= f.label :username, "Username:", class: "col-sm-2 control-label" %>
    <%= f.text_field :username, class: 'form-inline' %><br>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email:", class: "col-sm-2 control-label" %>
    <%= f.text_field :email, class: 'form-inline' %><br>
  </div>


  <div class="form-group">
    <%= f.label :password, "Password:", class: "col-sm-2 control-label" %>
    <%= f.password_field :password, class: 'form-inline' %><br>
    <%= f.submit "Register!" %>
  </div>
  <% end %>
</div>

cstor/app/views/users/show.html.erb
<div class="container-fluid">
  <h2><%= @show_user.username %>'s Profile</h2>
  <h3> Saved resources:</h3>
  <div class="panel panel-info">
    <% @user.liked_resources.each do |resource| %>
    <div class="panel-heading">
      <h3 class="panel-title"><a href="/resources/<%= resource.id%>"><%= resource.title %></a></h3>
    </div>
    <div class="panel-body">
      <p> <%= resource.abstract %> </p>
      <p> <em><%= resource.teacher.username %></em> </p>

      <% if !resource.likers.include?(current_user)%>

      <%= form_for :like, url: "/resources/#{resource.id}/likes" do |f| %>
      <%= f.submit "Like" %>
      <% end %>

      <% else %>

      <% if resource.like_by_user(current_user) != nil %>
      <%= form_for [resource, resource.like_by_user(current_user)], method: :delete do |f| %>
      <%= f.submit "Unlike" %>
      <% end %>
      <% end %>
      <% end %>
    </div>
      <% end %>

  </div>